[package]
name = "fo_client_converter"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"

[dependencies]
serde.workspace = true
serde_json.workspace = true
ron.workspace = true
fo_save_format = { path = "../", features = ["serde"] }
